<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/08/21 21:30:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=test',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
